services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatapp
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - chat-app
    restart: unless-stopped
  keycloak:
    container_name: keycloak-c-a
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - chat-app
    command:
      - "start-dev"

volumes:
  postgres:
    driver: local
networks:
  chat-app:
    driver: bridge